# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(max_length=50)),
                ('Sensor1', models.FloatField()),
                ('Sensor2', models.FloatField()),
            ],
        ),
    ]
