# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='RegistroSensores',
        ),
    ]
