# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_registrosensores_idlocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosensores',
            name='idLocal',
            field=models.IntegerField(null=True),
        ),
    ]
